site_name: Matthew McMillan's Knowledge Base
theme:

  palette:
    primary: 'blue'
    accent: 'orange'
  name: 'material'
  color: 'orange'
  logo:
    icon: 'queue'

markdown_extensions:
  - pymdownx.arithmatex
  - extra

extra_css:
  - css/style.css

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'